version: '3.9'

services:
  catalog-service:
    image: catalog-service
    hostname: catalog-service
    container_name: catalog-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://polar-postgres:5432/polardb_catalog
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_CLOUD_CONFIG_URI: http://config-service:8888
    ports:
      - 9001:9001
    depends_on:
      config-service:
        condition: service_healthy
  
  config-service:
    image: config-service
    hostname: config-service
    container_name: config-service
    ports:
      - 8888:8888
    healthcheck:
      test: ls /tmp/ || exit 1
      interval: 15s
      timeout: 105s
      retries: 5
      start_period: 30s

  polar-postgres:
    image: postgres:latest
    hostname: polar-postgres
    container_name: polar-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: polardb_catalog
    


  

      